server:
  port: 8080

is_server_running_behind_proxy: false

mongodb:
  connection_caching: true

web_app_host: 'http://localhost:3000'

logger:
  transports: ['console']

accounts:
  token_signing_key: 'JWT_TOKEN'
  token_expiry_days: 1
  token_expires_in_seconds: 3600
  # Generic test user setup (enabled in dev/preview only)
  create_test_user_account: false
  test_user:
    username: 'testuser'
    password: 'testpassword'
    full_name: 'Test User'

public:
  authenticationMechanism: 'EMAIL' #or 'PHONE'
  datadog:
    enabled: 'false'
