server:
  port: 8080

is_server_running_behind_proxy: false

mongodb:
  connection_caching: true

web_app_host: 'http://localhost:3000'

logger:
  transports: ['console']

accounts:
  token_signing_key: 'JWT_TOKEN'
  token_expiry_days: 1
  token_expires_in_seconds: 3600

public:
  authenticationMechanism: 'EMAIL' #or 'PHONE'
  datadog:
    enabled: 'false'

firebase:
  enabled: false
  cleanup_interval_days: 60