logger:
  transports:
    - 'console'
    - 'datadog'

sms:
  enabled: true

is_server_running_behind_proxy: true

public:
  authenticationMechanism: 'EMAIL' #or 'PHONE'
  default_otp:
    enabled: true
    code: '1234'

  # Generic test user setup (enabled in dev/preview only)
  accounts:
    create_test_user_account: true
    test_user:
      username: 'testuser'
      password: 'testpassword'
      full_name: 'Test User'
