name: clean_on_delete

on: delete

jobs:
  clean:
    # only run when deleting a branch
    if: github.event.ref_type == 'branch'
    uses: jalantechnologies/github-ci/.github/workflows/clean.yml@v3.1
    concurrency:
      group: ci-preview-${{ github.event.ref }}
      cancel-in-progress: true
    with:
      hosting_provider: DIGITAL_OCEAN    # Change to AWS to clean AWS resources if needed
      app_name: frm-boilerplate
      app_env: preview
      branch: ${{ github.event.ref }}
      docker_registry: ${{ vars.DOCKER_REGISTRY }}
      docker_username: ${{ vars.DOCKER_USERNAME }}
      do_cluster_id: ${{ vars.DO_CLUSTER_ID }}
    secrets:
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
      do_access_token: ${{ secrets.DO_ACCESS_TOKEN }}
